name: Generate and Commit
on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Установка зависимостей
        run: pip install -r src/synchronization/requirements.txt  
      
      - name: Запуск скрипта
        run: python src/synchronization/__main__.py 
        
      - name: Выгрузка дампа
        run: |
          mkdir -p dumps  
          mv books-dump-*.json dumps/
          
      - name: Сохранение в репозитории
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "feat: new dump" || exit 0
          git push
